### ISSUE TITLE
Introducing Filament Ambassadors with Whatsapp Groups with offensive participants that you can't ask for help....About the Filamentphp Brazil Group that received my request for help with irony and Sarcasm and idiotic things that Brazilians who know everything do

### ISSUE THREAD

**Issue by marcosdsdba** [AlexanderSix/alexandersix#1]
I know this isn't the right place, but I want to express my dissatisfaction here.

I asked a question about a problem with the display in a select multiple that showed several X's instead of grouping the options and users of the group, except for Leandro Ferreira
(https://twitter.com/leandrocfe) who was the only one who helped me. The others acted with harsh words, which should not be given to any human being.

I am very sad that nothing was done.

Well, it's Brazil, anything goes in the Banana Republic

WhatsappGroup Filamentphp Brazil: https://chat.whatsapp.com/IlIjAUEnY5M8JqXeM8xNRP

Attached down is the person apologizing to me after I had to retaliate to the insults
<img width="328" alt="image" src="https://github.com/user-attachments/assets/e1235dd8-9b61-44c1-a8bd-62498d617362">

**Comment by alexandersix** [comment]
@marcosdsdba 

1. You're right, this isn't the right place at all. Given that you acknowledged that this isn't the correct place and continued to open an issue anyways, I find this entire exchange highly unprofessional. There are appropriate avenues to take for expressing your dissatisfaction at a Filament initiative, but none of those avenues involve the Github README repositories for any of our core maintainers. In addition, even beyond opening this issue, changing the title, closing the issue, changing the title again, and re-opening this issue, sending me multiple notifications, is uncalled for.

2. You are also right, Leandro is a fantastic representative of the Filament community. That is why he is a Filament Ambassador. However, multiple people in the message chain were asking you to post the issue, show code examples, etc., so I don't find your claim that no one else was helping you to be entirely true. It is also important to note that I personally have no say whatsoever over any of the unofficial Filament community groups, including Filament Brazil.

3. We have spent a large amount of time tonight parsing through all of the chat logs from the interactions leading up to and shortly after the message you shared, and while I will not be passing judgement on what an appropriate level of sarcasm is, I encourage you to take a look at how you yourself handled the conversation. Coming in swinging with calling Filament "full of bugs" (which you are completely entitled to do if you so choose) and then firing back at people with insults that, according to multiple members of the community, crossed the line significantly will not win you any favors. Additionally, claiming homophobia in your original issue title without seemingly any evidence doesn't help your case. I will forever say that the Filament community needs to be welcoming and inclusive, and if some members are not living up to that, I apologize. However, as soon as you enter into the community and you are not living up to those standards as well, I can no longer help you.

---

So here's what is going to happen. I am going to lock this conversation and close this issue. You will not open another issue like this on any of my personal repositories or any personal repositories of any of the Filament core maintainers. If you would like to express praise, concern, suggestions, etc., you will use the official channels on Github or Discord in order to do so.

This issue shouldn't have even warranted a response, but I genuinely feel that if someone in the Filament community feels mistreated, they should be able to voice their feelings. However, you need to take the appropriate avenues for giving feedback. And again, if you are going to insult others and cross the line (talking about someone's sister, if I understood those messages correctly) with your responses, then I cannot help you much.
